name: superheroes
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3
  provider: ^6.0.2
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  network_image_mock: ^2.1.0


  flutter_lints: ^1.0.0



flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/images/

